import java.util.*;

public class QueueImplementation {
	
	public static void main(String args[]) {
		
		System.out.println("\n================== Queue Implementation =====================\n");

		PriorityQueue <Integer> queue1 = new PriorityQueue<Integer>();
		int k = 0;
		while(k < 10) {
			queue1.add(k); // Queue Follows FIFO Implementation so we use 
			k++;
		}
		System.out.print("Queue Generated By While Loop: ");
		System.out.println(queue1);

		
		System.out.println("\n================== ArrayDeQueue Implementation =====================\n");

		Deque <Integer> queue2 = new ArrayDeque<Integer>();
		k = 0;
		while(k < 10) {
			queue2.add(k); // Queue Follows FIFO Implementation so we use 
			k++;
		}
		System.out.print("DeQueue Generated By While Loop: ");
		System.out.println(queue2);
	}

}
